; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 632
=======
global g_ImportsGameVersion64 := 631
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""
global g_ImportsGameVersionPlatform64 := "Steam"